export const EVENT_CATEGORIES = [
  'Rock',
  'Pop',
  'Hip-Hop/Rap',
  'Electronic',
  'Techno',
  'House',
  'Trance',
  'Drum & Bass',
  'Country',
  'Jazz',
  'Blues',
  'Classical',
  'Opera',
  'Symphony',
  'Chamber Music',
  'Choral',
  'Metal',
  'Hardcore',
  'Punk',
  'Alternative',
  'Indie',
  'R&B',
  'Soul',
  'Funk',
  'Gospel',
  'Folk',
  'Bluegrass',
  'World',
  'Reggae',
  'Ska',
  'Latin',
  'Schlager',
  'Volksmusik',
  'Chanson',
  'Singer-Songwriter',
  'Karaoke',
  'Urban',
  'Comedy',
  'Stand-Up',
  'Improv',
  'Cabaret',
  'Theatre',
  'Musical',
  'Opera',
  'Operetta',
  'Circus',
  'Varieté',
  'Burlesque',
  'Magic',
  'Ballet',
  'Dance',
  'Contemporary Dance',
  'Modern Dance',
  'Tap Dance',
  'Flamenco',
  'Football',
  'Soccer',
  'Basketball',
  'American Football',
  'Baseball',
  'Ice Hockey',
  'Tennis',
  'Volleyball',
  'Handball',
  'Rugby',
  'Boxing',
  'MMA',
  'Wrestling',
  'Martial Arts',
  'Motorsports/Racing',
  'Auto Racing',
  'Motorcycle Racing',
  'Cycling',
  'Winter Sports',
  'Golf',
  'Equestrian',
  'Water Sports',
  'Extreme Sports',
  'Track & Field',
  'Gymnastics',
  'eSports',
  'Gaming',
  'Anime',
  'Family',
  'Children',
  'Literary Arts',
  'Fine Art',
  'Fashion',
  'Festival',
  'Club',
  'Outdoor',
  'Arena',
  'Stadium',
  'Party & Clubbing',
  'Essen & Trinken',
  'Workshops & Bildung',
  'Märkte & Messen',
  'Kunst & Ausstellung',
  'Nightlife & Afterwork',
  'Tiere & Freizeitparks',
  'Dating & Community',
  'Auto & Tuning',
  'Business & Networking',
  'Wellness & Gesundheit',
  'Yoga & Meditation',
  'Literatur & Bücher',
  'Film & Kino',
  'Spiritualität & Religion',
  'Politik & Diskussion',
  'Umwelt & Nachhaltigkeit',
  'Wohltätigkeit & Soziales',
  'Technologie & IT',
  'Wissenschaft & Forschung',
  'Reisen & Abenteuer',
  'Fotografie & Video',
  'Handwerk & DIY',
  'Spiele & Brettspiele',
  'Nachbarschaft & Gemeinschaft',
  'Studenten & Campus',
  'LGBTQ+',
  'Senioren & Rentner',
  'Haustiere & Tiere',
  'Garten & Natur',
  'Historische Events',
  'Stadtführungen & Touren',
  'Messen & Kongresse',
  'Vernissage & Ausstellungen',
  'Flashmob & spontane Treffen',
] as const;

export type EventCategory = typeof EVENT_CATEGORIES[number];
