export const SEASON_SPECIALS = [
  'Ostern',
  'Pfingsten',
  'Weihnachten',
  'Silvester',
  'Karneval/Fasching',
  'Halloween',
  'Oktoberfest',
  'Valentinstag',
  'Muttertag',
  'Vatertag',
  'Christi Himmelfahrt',
  'Advent',
  'Nikolaus',
  'Neujahr',
  'Heilige Drei Könige',
  'Gründonnerstag',
  'Karfreitag',
  'Walpurgisnacht',
  'Maifeiertag',
  'Fronleichnam',
  'Sommersonnenwende',
  'Johannistag',
  'Schulanfang',
  'Christopher Street Day',
  'Erntedankfest',
  'Tag der Deutschen Einheit',
  'Reformationstag',
  'Allerheiligen',
  'Martinstag',
  'Buß- und Bettag',
  'Heiligabend',
] as const;

export type SeasonSpecial = typeof SEASON_SPECIALS[number];
