#!/bin/bash

echo "========================================="
echo "JETZZ APP - Final GitHub Push"
echo "========================================="
echo ""
echo "✅ Build erfolgreich (npm run build)"
echo "✅ Alle Änderungen committed"
echo "✅ Ticket-System vollständig implementiert"
echo ""
echo "Pushe jetzt zu GitHub..."
echo ""

# Push zu GitHub
git push -u origin main --force

if [ $? -eq 0 ]; then
    echo ""
    echo "========================================="
    echo "🎉 ERFOLGREICH DEPLOYED!"
    echo "========================================="
    echo ""
    echo "✅ Code ist auf GitHub"
    echo "✅ Vercel deployt automatisch neu (2-3 Minuten)"
    echo "✅ Ticket-System ist live!"
    echo ""
    echo "Implementiert:"
    echo "- Web: /ticket/[token] - Vollständiger Live-Chat"
    echo "- App: app/ticket/[token].tsx - Native Chat"
    echo "- Real-time Updates via Supabase"
    echo "- Status-Tracking & Message History"
    echo ""
else
    echo ""
    echo "========================================="
    echo "Authentifizierung erforderlich"
    echo "========================================="
    echo ""
    echo "Erstelle ein GitHub Personal Access Token:"
    echo "1. Gehe zu: https://github.com/settings/tokens/new"
    echo "2. Token Name: 'Jetzz App'"
    echo "3. Wähle Scope: 'repo' (alle Checkboxen)"
    echo "4. Klicke 'Generate token'"
    echo "5. Kopiere das Token"
    echo ""
    echo "Dann erneut ausführen: ./FINAL-PUSH.sh"
    echo "Username: Dein GitHub Username"
    echo "Password: Das Token (nicht dein Passwort!)"
    echo ""
fi
